### ISSUE TITLE
NameError: name 'bnb' is not defined

### ISSUE THREAD

**Issue by vinay1986** [Reason-Wang/flan-alpaca-lora#1]
Getting the following error - 
 in <cell line: 8>:8                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/peft/peft_model.py:143 in from_pretrained                │
│                                                                                                  │
│   140 │   │   if config.task_type not in MODEL_TYPE_TO_PEFT_MODEL_MAPPING.keys():                │
│   141 │   │   │   model = cls(model, config)                                                     │
│   142 │   │   else:                                                                              │
│ ❱ 143 │   │   │   model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config)      │
│   144 │   │                                                                                      │
│   145 │   │   # load weights if any                                                              │
│   146 │   │   if os.path.exists(os.path.join(model_id, WEIGHTS_NAME)):                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/peft/peft_model.py:642 in __init__                       │
│                                                                                                  │
│   639 │   """                                                                                    │
│   640 │                                                                                          │
│   641 │   def __init__(self, model, peft_config: PeftConfig):                                    │
│ ❱ 642 │   │   super().__init__(model, peft_config)                                               │
│   643 │   │   self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_f   │
│   644 │   │   self.base_model.prepare_inputs_for_generation = self.prepare_inputs_for_generati   │
│   645 │   │   self.base_model_prepare_encoder_decoder_kwargs_for_generation = (                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/peft/peft_model.py:79 in __init__                        │
│                                                                                                  │
│    76 │   │   if isinstance(self.peft_config, PromptLearningConfig):                             │
│    77 │   │   │   self._setup_prompt_encoder()                                                   │
│    78 │   │   else:                                                                              │
│ ❱  79 │   │   │   self.base_model = LoraModel(peft_config, model)                                │
│    80 │   │   if getattr(self.peft_config, "modules_to_save", None) is not None:                 │
│    81 │   │   │   self.modules_to_save = self.peft_config.modules_to_save                        │
│    82 │   │   │   _set_trainable(self)                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/peft/tuners/lora.py:118 in __init__                      │
│                                                                                                  │
│   115 │   │   super().__init__()                                                                 │
│   116 │   │   self.peft_config = config                                                          │
│   117 │   │   self.model = model                                                                 │
│ ❱ 118 │   │   self._find_and_replace()                                                           │
│   119 │   │   mark_only_lora_as_trainable(self.model, self.peft_config.bias)                     │
│   120 │   │   self.forward = self.model.forward                                                  │
│   121                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/peft/tuners/lora.py:148 in _find_and_replace             │
│                                                                                                  │
│   145 │   │   │   │   │   is_target_modules_in_base_model = True                                 │
│   146 │   │   │   │   parent, target, target_name = self._get_submodules(key)                    │
│   147 │   │   │   │   bias = target.bias is not None                                             │
│ ❱ 148 │   │   │   │   if loaded_in_8bit and isinstance(target, bnb.nn.Linear8bitLt):             │
│   149 │   │   │   │   │   kwargs.update(                                                         │
│   150 │   │   │   │   │   │   {                                                                  │
│   151 │   │   │   │   │   │   │   "has_fp16_weights": target.state.has_fp16_weights,

**Comment by Reason-Wang** [comment]
It seems the error is related to "bitsandbytes". Have you installed it correctly?

**Comment by vinay1986** [comment]
Do you mean correct version?!

Can you tell me the required versions for bitandbytes and the accelerate packages?

**Comment by Reason-Wang** [comment]
For python 3.10, this works fine for me:

torch==1.13.1
transformers==4.29.1
accelerate==0.19.0
peft==0.3.0
bitsandbytes==0.38.1

**Comment by vinay1986** [comment]
Thanks this works :)
