### ISSUE TITLE
flan-alpaca-gpt4-lora-xl on Google colab

### ISSUE THREAD

**Issue by vinay1986** [Reason-Wang/flan-alpaca-lora#2]
Can  reasonwang/flan-alpaca-gpt4-lora-xl be run on Google colab?

If yes, what setting / config would it require?

I tried A100 and it seems to fail 😔

**Comment by Reason-Wang** [comment]
Runing the xl version on Google colab is attractive. I am using free version of colab so my cpu ram and gpu ram is limited. As I experimented, the reason to fail is the model need to be load to cpu first, then quantize to 8bit version. But the cpu ram is not large enough to load the whole model, so the kernel crushed. I just upload a 8bit version of flan-t5-xl, which is much smaller. You can directly use this model as the base model. With this the model can be run on a free version colab.

The model is "reasonwang/flan-t5-xl-8bit"
The code is:
```python
import transformers
from peft import PeftModel
import torch

model_name = "reasonwang/flan-t5-xl-8bit"; peft_model_id = "reasonwang/flan-alpaca-gpt4-lora-xl"
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
base_model = transformers.AutoModelForSeq2SeqLM.from_pretrained(model_name)

peft_model = PeftModel.from_pretrained(base_model, peft_model_id)
inputs = tokenizer("If you are the president of a developing country, what you will do to make your country better?", return_tensors="pt")
for k, v in inputs.items():
    inputs[k] = v.to("cuda")
outputs = peft_model.generate(**inputs, max_length=256, do_sample=True)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))
```

**Comment by vinay1986** [comment]
Thanks let me give this a shot

**Comment by vinay1986** [comment]
Thanks this works 👍🏼
